"""add election_admins association table and election fields

Revision ID: 20251229_add_election_admins_and_columns
Revises: 
Create Date: 2025-12-29 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20251229_add_election_admins_and_columns'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to elections table
    op.add_column('elections', sa.Column('name', sa.String(), nullable=True))
    op.add_column('elections', sa.Column('contract_address', sa.String(), nullable=True))

    # Create election_admins association table
    op.create_table(
        'election_admins',
        sa.Column('election_id', sa.Integer(), sa.ForeignKey('elections.id'), primary_key=True, nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), primary_key=True, nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('election_admins')
    op.drop_column('elections', 'contract_address')
    op.drop_column('elections', 'name')
    # ### end Alembic commands ###
